// 인증없이 접근가능 페이지
export const AUTH_EXCLUSIONS_ROUTER_NAME = [
  'dashboard',
  'login',
  'loginResult',
  // 'loginGoogleResult',
  // 'loginLineResult',
  'RegisterSelect',
  'personalRegister',
  'companyRegister',
  'userRegisterComplete',
  'companyRegisterComplete',
  'findId',
  'findPassword',
  'resetPassword',
  'findIdResult',
  'findPasswordResult',
  'InquiryPage',
  'FaqPage',
  'PrivacyPolicy',
  'TermsOfService',
  /* 이상 로그인 없이 접근 가능 */
  // 'userIndex',
  // 'businessIndex',
  // 'Resume',
  // 'JobOffers',
  // 'UserPage',
  // 'CompanyList',
  // 'SupportDetail',
  // 'CreateInterviewOffer',
  // 'CompanyInfoPage',
  // 'TalentSearchPage',
  // 'InterviewOffers',
  // 'InterviewResults',
  // 'JobSeekerInterviews',
  // 'FaqPage',
  // 관리자 페이지
  'Admin'
  // 'AdminFaq',
  // 'AdminUserMng',
  // 'AdminInquiries',
  // 'AdminBusinessApplications',
];
