// 인증없이 접근가능 페이지
export const AUTH_EXCLUSIONS_ROUTER_NAME = [
  'dashboard',
  'login',
  'loginGoogleResult',
  'loginLineResult',
  'RegisterSelect',
  'personalRegister',
  'businessRegister',
  'userRegisterComplete',
  'businessRegisterComplete',
  /* 이상 로그인 없이 접근 가능 */
  'userIndex',
  'businessIndex',
  'findId',
  'findPassword',
  'findIdResult',
  'findPasswordResult',
  'Resume',
  'JobOffers',
  'UserPage',
  'CompanyList',
  // 'SupportDetail',
  'CreateInterviewOffer',
  'CompanyInfoPage',
  'FaqPage',
  'InquiryPage',
  'TalentSearchPage',
  'InterviewOffers',
  'AdminFaq',
  'admin',
  'AdminUserMng',
  'InterviewResults',
  'JobSeekerInterviews',
  'AdminBusinessApplications'
];
